import './globals.css'
import {i18n} from "../../../i18n"
import {Header} from "@/app/[lang]/components/Header";
import {Footer} from "@/app/[lang]/components/Footer";
import {NextIntlClientProvider} from 'next-intl/client'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const generateStaticParams = async () => {
  return i18n.locales.map((locale)=>({ lang: locale }))
}


export default async function RootLayout({ children, params: {lang} }) {

  let messages;
  try {
    messages = (await import(`../../messages/${lang}.json`)).default;
  } catch (error) {

  }

  return (
    <html lang={lang}>
      <body>
      <NextIntlClientProvider locale={lang} messages={messages}>
        <Header />
        {children}
        <Footer />
      </NextIntlClientProvider>
      </body>
    </html>
  )
}
