import Head from 'next/head'
import AppLayout from '../components/Layouts/AppLayout'

export default function Home() {
  return (
    <AppLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h2 >
          Homepage
        </h2>
      </main>

      
    </AppLayout>
  )
}
